CREATE DATABASE BBTS;

USE BBTS;

CREATE TABLE COLABORADOR (
    ID_COLABORADOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    SITUACAO_CADASTRO VARCHAR(50),
    SENHA VARCHAR(255),
    CARGO VARCHAR(30),
    DEPARTAMENTO VARCHAR(40)
);

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
	ID_COLABORADOR INT NOT NULL,
    NOME_FANTASIA VARCHAR(150),
    RAZAO_SOCIAL VARCHAR(150),
	CNPJ VARCHAR(20),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(11),
	SITE_INSTITUCIONAL VARCHAR(255),
    CEP VARCHAR(8),
	RUA VARCHAR(150),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    UF VARCHAR(2),
    FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR(ID_COLABORADOR)
);

CREATE TABLE REGISTRO_EMPRESARIAL (
    ID_REG_EMP INT AUTO_INCREMENT PRIMARY KEY,
	ID_FORNECEDOR INT UNIQUE NOT NULL,
    PORT_EMP VARCHAR(50),
    REGIAO_ATUACAO VARCHAR(100),
    NATUREZA_JURIDICA VARCHAR(100),
    CNAE_1 VARCHAR(20),
    CNAE_2 VARCHAR(20),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

CREATE TABLE AUDITORIA_PESQUISA (
    ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PESQUISA DATE,
    JUSTIFICATIVA_PESQUISA TEXT(250),
    STATUS VARCHAR(50)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO TEXT(200),
    SITUACAO VARCHAR(50)
);

CREATE TABLE CLASSIFICACAO (
    ID_CLASSIFICACAO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO TEXT(200),
    SITUACAO VARCHAR(50),
    ID_CATEGORIA INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE ITENS_PRODUTO (
    ID_ITENS_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150),
    DESC_TECNICA TEXT(200),
    UNIDADE_MEDIDA VARCHAR(20),
    PALAVRAS_CHAVE VARCHAR(255),
    ID_CLASSIFICACAO INT NOT NULL,
    FOREIGN KEY (ID_CLASSIFICACAO) REFERENCES CLASSIFICACAO(ID_CLASSIFICACAO)
);

CREATE TABLE PESQUISA_PRODUTO (
    ID_PESQUISA_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_PESQUISA VARCHAR(100),
    DESCRICAO TEXT(250),
    ID_ITENS_PRODUTO INT NOT NULL,
    FOREIGN KEY (ID_ITENS_PRODUTO) REFERENCES ITENS_PRODUTO(ID_ITENS_PRODUTO)
);

CREATE TABLE ITENS_PALAVRA_CHAVE(
ID_PALAVRA_CHAVE INT AUTO_INCREMENT PRIMARY KEY,
PALAVRA VARCHAR(20),
ITEN_CORRESPONDENTE INT,
FOREIGN KEY (ITEN_CORRESPONDENTE) REFERENCES ITENS_PRODUTO(ID_ITENS_PRODUTO)
);

CREATE TABLE MARCA (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO TEXT(200),
    SITUACAO VARCHAR(50)
);

CREATE TABLE MARCA_ITENS (
    ID_MARCA INT,
    ID_ITENS_PRODUTO INT,
    PRIMARY KEY (ID_MARCA, ID_ITENS_PRODUTO),
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
    FOREIGN KEY (ID_ITENS_PRODUTO) REFERENCES ITENS_PRODUTO(ID_ITENS_PRODUTO)
);

CREATE TABLE RESULTADO_PESQUISA (
    ID_RESULTADO_PESQUISA INT AUTO_INCREMENT PRIMARY KEY,
    SITE_PESQUISA VARCHAR(150),
    TITULO_ANUNCIO VARCHAR(200),
    DESCRICAO_ANUNCIO TEXT,
    DESCRICAO_PRODUTO TEXT,
    PRECO DECIMAL(10,2),
    URL_PRODUTO VARCHAR(255),
    DATA_RESULTADO DATE,
    STATUS_VALIDACAO VARCHAR(50),
    ID_PESQUISA_PRODUTO INT NOT NULL,
    FOREIGN KEY (ID_PESQUISA_PRODUTO) REFERENCES PESQUISA_PRODUTO(ID_PESQUISA_PRODUTO)
);

CREATE TABLE ITENS_SELECIONADOS(
ID_ITENS_SELECIONADOS INT AUTO_INCREMENT  PRIMARY KEY,
ID_RESULTADO INT,
ID_RESPONSAVEL INT,
DATA_SELECAO DATETIME,
FOREIGN KEY (ID_RESULTADO) REFERENCES RESULTADO_PESQUISA(ID_RESULTADO_PESQUISA),
FOREIGN KEY (ID_RESPONSAVEL) REFERENCES COLABORADOR(ID_COLABORADOR)
);

CREATE TABLE ITENS_DESCARTADOS(
ID_ITENS_DESCARTADOS INT AUTO_INCREMENT PRIMARY KEY,
ID_RESULTADO INT,
ID_RESPONSAVEL INT,
DATA_DESCARTE DATETIME,
JUSTIFICATIVA TEXT(255),
FOREIGN KEY (ID_RESULTADO) REFERENCES RESULTADO_PESQUISA(ID_RESULTADO_PESQUISA),
FOREIGN KEY (ID_RESPONSAVEL) REFERENCES COLABORADOR(ID_COLABORADOR)
);
